spring:
  application:
    name: SuperMarketGateway

server:
  port: 2020


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true


zuul:
  routes:
    checkout-service:
      path: /checkout/**
      serviceId: CHECKOUT-SERVICE
      stripPrefix: true